title : Andy's blog
tagline: Blog Tagline
author :
  name : Andy Wu	
  email : icetortoise@gmail.com
  github : icetortoise
  twitter : icetortoise
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
